version: '3'
services:
  frontend:
    image: frontend_cervezas  
    hostname: frontend
    container_name: frontend_app
    ports:
      - "80:80"
    networks:
      - mi-red
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:7024

  backend:
    image: backend_cervezas 
    hostname: backend
    container_name: backend_app
    ports:
      - "7024:7024"
    networks:
      - mi-red

networks:
  mi-red:
    driver: bridge
